### ISSUE TITLE
FYSIQ FW-ONEPRO Sensors show unknown

### ISSUE THREAD

**Issue by CaptainMalu** [dudanov/hassio-ftms#1]
hi,
I got the FYSIQ FW-ONEPRO treadmill today.
Your integration found the device directly and start/stop of the training work fine.
But i can't set the speed and all sensor like distance, eapsed time and so on show unknown.

I'm not sure what information I can provide to help.
Please, let me know.
![Screenshot from 2024-07-26 14-02-09](https://github.com/user-attachments/assets/8f6f14c6-d6fe-4885-80a9-9619cfbddb30)

**Comment by dudanov** [comment]
Hi. Please try to install integration from `master` branch. Integration is under development.

**Comment by CaptainMalu** [comment]
thank you that helped a lot.
I thought I used main, because I overlooked the setting and HACS used 0.9 as default.
