### ISSUE TITLE
HACS shows v0.9 as update, when main is installed

### ISSUE THREAD

**Issue by CaptainMalu** [dudanov/hassio-ftms#2]
Hi,
I have two problems.
First in v0.9 no senor for my treadmill is working but with the main branch it's fine.
Could you release a v0.10 so HACS isn't downgrading constantly.

And my second problem is, that ftms can't find the treadmill often times.
We placed an esphome bluetooth proxy near the machine but after some time turned of the machine isn't recognized anymore.

Device info
FS-BT-T4
by FITSHOW
Firmware: 1.2.9
Hardware: 1.0
Serial number: FS230911001

**Comment by dudanov** [comment]
Hi,
I release v0.10 that includes all the latest features.

> And my second problem is, that ftms can't find the treadmill often times.
> We placed an esphome bluetooth proxy near the machine but after some time turned of the machine isn't recognized anymore.

Hmm... I use HASS core Bluetooth API. Please send your logs filtered by ftms component.
