### ISSUE TITLE
Sensors not working on Urevo Spacewalk 3S

### ISSUE THREAD

**Issue by quack3d** [dudanov/hassio-ftms#3]
Just got a Urevo Spacewalk 3S. All the controls are working but none of the sensors. They just show 0. Here is output from nRF Connect:

![image](https://github.com/user-attachments/assets/81abafa6-bb19-4c1d-9815-87097343f662)

**Comment by dudanov** [comment]
Hello, @quack3d .
How does HASS determine this fitness machine? Like a treadmill?
Please send filtered HASS logs, with debug level enabled for the `ftms` component.
The reason may be that the controller does not exactly match the FTMS specification in terms of determining the type of fitness machine.

**Comment by quack3d** [comment]
Yeah, as a treadmill. Now when I tried to turn it on it won't stay connected for more than a second. I tried turning it off and on several times. Then I restarted HA and was able to turn it on through HA even though logs are still full of errors. The "A message handler raised an exception:" has now been seen 800 times HA says. Here is log from before I restarted HA. https://dpaste.org/gKQOQ

**Comment by dudanov** [comment]
Deserialization error. Unparsed data remains.
You need to set the `pyftms` library logging level to `DEBUG` to see the raw data. I added a commit to the `main` branch that do that. Please update component from the `main` branch `not version`, make sure that the `HASS` log shows logs from the `pyftms` library. Then send me the logs so I can understand the problem.

**Comment by quack3d** [comment]
Like so? https://dpaste.org/thfuT

**Comment by dudanov** [comment]
@quack3d try new version 0.11.

**Comment by quack3d** [comment]
Thanks! Now at least these sensors work: Distance total, Energy total, Inclination, Speed, Time elapsed. Here are some logs if interesting: https://dpaste.org/Ko7SA

Oh btw: If selecting step_count I couldn't get the integration to start at all. I got a KeyError: 'step_count': https://dpaste.org/7in3j

However, I can't get the connection to be stable. If I restart HA, start treadmill, it will connect fine. But sometimes when I turn off and on power to treadmill it will try over and over to connect but it fails (even when power off - on multiple times). If I remove the treadmill from custom component and re-add (without restarting) the connection works again. But I can do some more testing and perhaps raise a different issue on this. I haven't find a way to reproduce it consistently (yet).

**Comment by dudanov** [comment]
> Oh btw: If selecting step_count I couldn't get the integration to start at all. I got a KeyError: 'step_count': https://dpaste.org/7in3j

Fixed in `v0.12`.

**Comment by dudanov** [comment]
> However, I can't get the connection to be stable. If I restart HA, start treadmill, it will connect fine. But sometimes when I turn off and on power to treadmill it will try over and over to connect but it fails (even when power off - on multiple times). If I remove the treadmill from custom component and re-add (without restarting) the connection works again. But I can do some more testing and perhaps raise a different issue on this. I haven't find a way to reproduce it consistently (yet).

I use the recommended technique of restarting the component when the connection is broken. In this case, HASS takes over the periodic attempts to establish a connection.
I do not turn off my fitness equipment, so such problems do not arise.

Let's close this issue and create a new one on this topic. If you can track down the patterns and recreate the problem, that would be ideal.
