### ISSUE TITLE
Feature request: Keep numbers in sync with sensors

### ISSUE THREAD

**Issue by quack3d** [dudanov/hassio-ftms#7]
Sorry for pestering you with requests - this is just such a great component. I really appreciate your effort. 😊

Could you make number.treadmill_inclination and number.treadmill_speed automatically update state with the data from sensor.treadmill_inclination and sensor.treadmill_speed? Or is this not good practice?

**Comment by dudanov** [comment]
Ok, let's try to implement synchronization. I had such an idea, but the potential ambiguity of the equipment behavior held me back. If there are people who complain about this functionality, I will bring it out in the integration settings option.

Try version `0.4`.
